name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      # ✅ Install Chrome & ChromeDriver automatically (works reliably)
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Verify versions
        run: |
          google-chrome --version
          chromedriver --version

      # ✅ Run your Selenium tests in headless mode
      - name: Run Selenium tests (headless)
        env:
          DISPLAY: ":99"
        run: |
          pytest --maxfail=1 --disable-warnings -q
